# Generated by Django 4.2.5 on 2023-09-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
    ]
